### ISSUE TITLE
Funding not working in sandbox v2

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#121]
In sandbox v2, when requesting an entry node the node that is returned is not being funded.

## Expected Behavior

When requesting an entry node the node should go to status funding and the funding service should receive this request. When the funding service receives a request it is stored in the `requests` table and it should also execute a transaction on the hardhat node running in pluto.

## Current Behavior

Discovery platform sets the node to status "FUNDING" but the funding service is not receiving anything in order to actually fund the node.

## (Optional) Possible Solution

The funding service api module in discovery platform is trying to reach funding service but it cannot, this can be a docker network issue or just the url that we are trying to reach does not exist.

## Steps to Reproduce

1. run sandbox v2
2. request an entry node doing the following post request ``` curl --request POST \
  --url http://localhost:3020/api/request/entry-node \
  --header 'Content-Type: application/json' \
  --data '{
	"client": "sandbox"
}'```

**Comment by nionis** [comment]
Fixed by https://github.com/Rpc-h/RPCh/pull/115
