### ISSUE TITLE
SDK selecting same entry node and exit node

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#123]
When sdk start runs, it can sometimes select the same entry node as exit node.

## Expected Behavior

sdk should select a different entry node and a different exit node.

## Current Behavior

sdk requests an entry and exit node but there is no check in case they are the same

This could be fixed by checking the selection of the exit node and making sure it is different to entry node

## Steps to Reproduce

1. run sdk start
2. check if entry node and exit node is the same

**Comment by nionis** [comment]
Fixed by #125
