### ISSUE TITLE
Discovery platform not updating status after funding nodes

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#124]
After funding a node discovery platform updates node status to funding but does not update the node after funding has passed or failed
## Expected Behavior
Discovery platform should update the status of the node after the funding request has completed to "READY" or "UNUSABLE"

## Current Behavior
Node status is stuck on funding after being selected as entry node

## Steps to Reproduce

1. Request entry node
2. Check status of the selected entry node before funding and after

**Comment by nionis** [comment]
Fixed by https://github.com/Rpc-h/RPCh/pull/115
