### ISSUE TITLE
Build container images and helmfiles for RPCh related apps 

### ISSUE THREAD

**Issue by sitilge** [Rpc-h/RPCh#128]
### Description

Build container images and helmfiles for RPCh related apps - funding service, discovery service, exit node. Deploy the Helm charts in a Kubernetes cluster.

### Relevant issues

- Build container images for RPCh artifacts:
  - Funding Service
  - Discovery Service
  - HOPRd nodes
  - RPCh exit node
- Build a Helm chart for Funding service
  - 1x endpoint, possibly replicas for reliability
- Build a Helm chart for discovery service
  - 1x endpoint, possibly replicas for reliability
- Build a Helm chart for HOPRd node
  - Deploy 3x entries
- Build a Helm chart for RPCh exit node
  - Deploy 3 pairs of RPCh exit node and hoprd nodes, a pod with two containers (exit node + HOPRd node), tightly coupled.

### Definition of DONE

Container images are built from Github pipeline and pushed to our public GCP container registry. Helmfiles are pushed to the monorepo. Later on, the Helm charts should be deployed to a Kubernetes cluster and scaled accordingly.

**Comment by nionis** [comment]
Work completed in https://github.com/Rpc-h/infrastructure
