### ISSUE TITLE
RPCh docs

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#143]
### Description

This `epic` encapsulates the work that needs to be done in order to get docs.rpch.net ready for Alpha.

### Relevant issues

- implement https://docusaurus.io/docs in a new repository `documentation`
- integrate the repository with Vercel
- give access to Hammad
- with the help of Hammad, find out which content RPCh needs to create for this documentation (guides, etc)
- sync with RPCh team on the things that need to be done by RPCh
- update this epic with new tasks once synced with RPCh team

### Definition of DONE

Once documentation is hosted for Alpha.

**Comment by nionis** [comment]
@mjadach-iv Hammad has sent me the list of questions:

```
How do users self-integrate RPCh once they are on the access page, need a walk-through from minting the token
With only HOPR-controlled nodes on the discovery platform, will the registration function be off? Will users be able to register still, and we’ll parse nodes on our end?
What infrastructure is the funding service run on / what does the payment gateway for clients look like / how do we add funds to the funding service
What infrastructure is the discovery platform run on / where is the data stored
High-level short explanation of what kevlar/helios do / how they verify RPC response integrity
A few general questions: NIRP / honesty score won’t be in the release, so I assume subgraph indexer won’t either – just quick double check on what's going out on the alpha and how much node runners can interact with it or register themselves etc..

You were right to do it this way, were a couple of things that came up when fleshing it out. But mainly need a walkthrough of self-registration for degens and an overview of the funding service / client DB + future payment gateway. Everything else should be like a quick touch on the topic. Let me know when you'd be free for a call. Maybe tomorrow?
```

**Comment by mjadach-iv** [comment]
> How do users self-integrate RPCh once they are on the access page, need a walk-through from minting the token

1. User opens a page and clicks 'get token'
2. user downloads docker (`docker pull <some-name-rpc-related>`
3. users runs the docker image with the token

> With only HOPR-controlled nodes on the discovery platform, will the registration function be off? Will users be able to register still, and we’ll parse nodes on our end?

Which registration function? Registration of HOPR nodes, registration of B2D users?

> What infrastructure is the funding service run on / what does the payment gateway for clients look like / how do we add funds to the funding service

Funding service will be will be running on our K8s cluster and that cluster will be running on GCP.

> What infrastructure is the discovery platform run on / where is the data stored

Siscovery platform will be will be running on our K8s cluster and that cluster will be running on GCP.
Data will be stored on PostreSQL on GCP.

> High-level short explanation of what kevlar/helios do / how they verify RPC response integrity

Kevlar/Helios converts any RPC endpoint into a safe unmanipulable RPC for its users. It syncs fast and is lightweight. 


> A few general questions: NIRP / honesty score won’t be in the release, so I assume subgraph indexer won’t either -  just quick double check on what's going out on the alpha and how much node runners can interact with it or register themselves etc..

The subgraph is still a Draft in the specification and we didnt even create a task for it yet


@nionis please provide more info where you feel its necessary, or I as simply wrong

**Comment by nionis** [comment]
@mjadach-iv thanks

> With only HOPR-controlled nodes on the discovery platform, will the registration function be off? Will users be able to register still, and we’ll parse nodes on our end?

No registration of HOPRd nodes in the RPCh ecosystem

> What infrastructure is the funding service run on / what does the payment gateway for clients look like / how do we add funds to the funding service

There is no payment gateway right now, planned for Q2 2023. Adds are added by deals made from Rik & Seb and we manually update the DB with the quota purchased.

> High-level short explanation of what kevlar/helios do / how they verify RPC response integrity

Slight correction from Michal's answer, Kevlar & Helios verify that an ethereum RPC response is correct & untampered in any way.

**Comment by nionis** [comment]
Closing this issue since the work from RPCh front was done, will open an new epic for some new things we should be doing in March.
