### ISSUE TITLE
E2E tests failing

### ISSUE THREAD

**Issue by sitilge** [Rpc-h/RPCh#152]
## Expected Behavior

E2E tests are not failing.

## Current Behavior

E2E tests are failing.

## (Optional) Possible Solution

Maybe trying to play around with the SDK timeout. It could be a transient bug.

## Steps to Reproduce

1. Run E2E tests via the pipeline

2. _Were you able to reproduce the bug using the above steps consistently each time?_ **NO**

3. I ran into the same problem yesterday, and something in the chain is giving flaky results.

## Context (Environment)

Github pipelines.

## Logs

https://github.com/Rpc-h/RPCh/actions/runs/3997803450/jobs/6859697788

**Comment by nionis** [comment]
Thank you for creating the issue @sitilge :)
