### ISSUE TITLE
Handle no available entry node

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#153]
When asking for an entry node from Discovery Platform, it is possible that it returns without an actual entry node. This can happen because the exclude list or none are in "READY" status

### Describe the feature you'd like

DP should return an status code 404 when no entry node is available and it should be handled in sdk so it does not error out.

### Additional context

While looking at handling this use case, it can be useful to check what status codes DP is returning and correct them if they are not correct

**Comment by nionis** [comment]
Fixed via #127
