### ISSUE TITLE
Re selection of entry node can choose the current exit node

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#159]
When an entry node is no longer fresh and has a low reliability score it is deemed as unreliable and should be changed for a new reliable entry node. However this re selection only makes sure that you can not get your old entry node again but you can get your current exit node. The problem here is that with hoprd messages fail is the recipient and destination are the same.

## Expected Behavior

Choose a new entry node that is neither the old unreliable node or the current exit node

## (Optional) Possible Solution

Use exclude list parameter to select a new entry node that follows the expected behavior

## Steps to Reproduce

1. run bw
2. make current entry node unreliable by turning it off and also make all other nodes that are not the exit node unavailable by changing their state manually in DB to something that is not "READY". It is done this way for bw integration, to check this manually you can just send all nodes that are not the exit node in the exclude list.

**Comment by nionis** [comment]
We will need to close this in favor of https://github.com/Rpc-h/RPCh/issues/159
