### ISSUE TITLE
Number into BigInt

### ISSUE THREAD

**Issue by ItsLuized** [Rpc-h/RPCh#177]
In the future, the currency we will be using will be based on WEI, which the minimum value is represented by 10^18. This means the Number data type from JS/TS will no be sufficient and will overflow. 

In our case, the maximum number we would use safely, would be represented by ```Number.MAX_SAFE_INTEGER``` which is: 9007199254740991, taking this into account, the number data type can't safely handle the representation of 1 token in WEI.

### Describe the feature you'd like

The funds, quota and anything related to currency to be represented as BigInt.

### Additional context

"Safe" in this context refers to the ability to represent integers exactly and to compare them correctly. For example, ```Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2``` will evaluate to true, which is mathematically incorrect. 

Even though the ```Number.MAX_VALUE``` is bigger, its not accurate anymore, and any value bigger than it is represented as ```Infinity```

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

As we internally use mHOPR, according to the contract it uses 18 decimal places. So WEI is the way to correctly handle these values as precise as possible.
Source: https://gnosisscan.io/token/0x66225de86cac02b32f34992eb3410f59de416698?a=0x1f5deee62c65577802e3b15c3f2e523b2b772458#code

**Comment by ItsLuized** [comment]
We could change the data type in PostgreSQL:
- In the `requests` table, the field `amount` change from to a numeric(78).
- In the `funding_request`, the field `amount` change from text to numeric(78).
- In the `quotas` table, the field `quota` change from integer to numeric(78).
- In the `registered_node` table, the field `total_amount_funded` change form numeric to numeric(78).

In Typescript:
- Changes from discovery-platform:
  - In `funding-requests` DTOs: `QueryFundingRequest` and `CreateFundingRequest` change the field `amount` from `string` to `bigint`
  - In `funding-service-api` DTOs:
    - `getAccessTokenResponse` and `postFundingResponse` change field `amountLeft` from `number` to `bigint`
    -  `postFundingRequest` and `getRequestStatusResponse` change field amount from `string` to `bigint`
  - In `graph-api` DTOs: `GetAccountChannelsResponse` and `getAccountsFromBlockChangeResponse` change field `balance` from `number` to `bigint`
  - In `quota` DTOs: `CreateQuota` and `QueryQuota` change field `quota` from `number` to `bigint`
  - In `registered-nodes` DTOs: `QueryRegisteredNode` change field `total_amount_funded` from `number` to `bigint`

- Changes from funding-service:
  - In `request` DTOs: `Request` and `QueryRequest` change the field `amount` from `string` to `bigint`

**Comment by nionis** [comment]
SGTM please go ahead with PR
