### ISSUE TITLE
Riga pluto anvil network is not found

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#195]
When funding service tries to fund entry nodes it fails because network can not be found.
## Expected Behavior

Funding service should be able to fund entry nodes.
## Current Behavior

Funding service can not find network.
## (Optional) Possible Solution

Possibly the port that used to work with previous versions of `pluto` is not the same. Right now port `8545` is being used.
## Steps to Reproduce

1. Run sandbox 
2. Get an entry node by running `curl --request POST \
  --url http://localhost:3020/api/v1/request/entry-node \
  --header 'Content-Type: application/json' \
  --data '{
	"client": "sandbox"
}'`
3. Get access token from funding service `curl --request GET \
  --url http://localhost:3010/api/access-token`
4. Check funding request that was created by running `curl --request GET \
  --url http://localhost:3010/api/request/status \
  --header 'x-access-token: YOUR_ACCESS_TOKEN'` 

Easier way to check that no network is online on port 8545

1. run sandbox and make sure port 8545 is being forwarded on `pluto` image
2. make an rpc request from host machine `curl --request POST \
  --url http://127.0.0.1:8545/ \
  --header 'Content-Type: application/json' \
  --data '{
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": []
}'`
_Were you able to reproduce the bug using the above steps consistently each time?_ **YES**

## Logs

```
[
	{
		"id": 1,
		"access_token_hash": "TkkR57Er9r4alvyx9vR6K+tGA4MSMMWRA9olxvauRPQ=",
		"created_at": "2023-02-08T20:30:17.612Z",
		"updated_at": "2023-02-08T20:30:17.612Z",
		"node_address": "0xaae1a05e56892a89f65e13a07ecd0f5efe206f72",
		"amount": "3",
		"transaction_hash": null,
		"chain_id": 1,
		"reason": "could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.7.2)",
		"status": "FAILED-DURING-PROCESSING"
	},
	{
		"id": 2,
		"access_token_hash": "TkkR57Er9r4alvyx9vR6K+tGA4MSMMWRA9olxvauRPQ=",
		"created_at": "2023-02-08T20:30:31.336Z",
		"updated_at": "2023-02-08T20:30:31.336Z",
		"node_address": "0xaae1a05e56892a89f65e13a07ecd0f5efe206f72",
		"amount": "3",
		"transaction_hash": null,
		"chain_id": 1,
		"reason": "could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.7.2)",
		"status": "FAILED-DURING-PROCESSING"
	}]
```

## Current docker compose setup
 - [funding service](https://github.com/Rpc-h/RPCh/blob/47da29d73c2cbcbce9b53a5602402c563f44fcf1/devkit/sandbox/src/central-docker-compose.yml#L27)
 - [pluto](https://github.com/Rpc-h/RPCh/blob/47da29d73c2cbcbce9b53a5602402c563f44fcf1/devkit/sandbox/src/nodes-docker-compose.yml#L37)

**Comment by nionis** [comment]
might be that we force chain ID ?

**Comment by diegoalzate** [comment]
This is not the case because we can't do any rpc calls to port 8545. Nothing responds if we try to communicate directly to the endpoint. That could have been the case if we could communicate with the rpc server directly and not through funding service.
