### ISSUE TITLE
Can not handle massive requests

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#210]
When trying to send a request with more than 400 segments per message it seems that this clogs up the whole network and it can make all other requests slow plus the massive request rarely goes through.
## Expected Behavior

We should be able to handle massive requests or at least not make everything else fail.
## Current Behavior

It seems that this request can cause a sort of DDOS response from sdk/hoprd where this request from a wallet will be retried and either the sdk or hoprd can not handle this request. It is important to know where the holdup actually happens.
## Logs

![image](https://user-images.githubusercontent.com/22416585/218260301-54051f43-7ffa-4524-9d00-1f6b565f75a9.png)

![image](https://user-images.githubusercontent.com/22416585/218260308-44a7335a-ae37-44e0-9cfd-8b30d4b77ce0.png)

**Comment by nionis** [comment]
@esterlus might be fixed with the new patch

**Comment by esterlus** [comment]
not sure about it - we would need to test it again
