### ISSUE TITLE
sending hoprd messages being stalled by chrome

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#212]
When sending a couple F.A.Rs chrome can sometimes stall these requests. 
## Expected Behavior

We should be able to handle the stalling or add throttle
## Current Behavior

Requests fails

## Steps to Reproduce

1. run sandbox and bw
2. open cow swap and connect wallet
3. press the coin selector in cow swap multiple times (an operation here sends about 400 messages)
4. check network stats

_Were you able to reproduce the bug using the above steps consistently each time?_ **NO**

## Logs

![image](https://user-images.githubusercontent.com/22416585/218282471-c33a0f35-f7b2-4cb3-b143-ab0f0fe6778e.png)

chrome logs about stalling: https://developer.chrome.com/docs/devtools/network/reference/#timing-explanation

**Comment by nionis** [comment]
can be circumvent by using the new websocket API
