### ISSUE TITLE
Message verification failed error from crypto lib

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#228]
## Overview

When receiving a response it is possible that crypto throws a `message verification failed` error. 

This happens because of any or both of these reasons:
- the counter we use when when we unbox the response is somehow wrong
- the counter within the response (given by exit-node) is somehow wrong

### Log
search for `failed to decrypt message`
[failed-verification.log](https://github.com/Rpc-h/RPCh/files/10769336/failed-verification.log)

**Comment by nionis** [comment]
Might be related to https://github.com/Rpc-h/RPCh/issues/189

**Comment by diegoalzate** [comment]
This has been solved in a crypto pr https://github.com/Rpc-h/crypto/pull/14
