### ISSUE TITLE
Pushing some images to Docker Hub (rpch account)

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#239]
Right now we have a command `docker pull europe-west6-docker.pkg.dev/rpch-375921/rpch/rpc-server:<TAG>`
I propose using a mirror on docker hub on our rpch account and we would get: `docker pull rpch/rpc-server:<TAG>` for external use.

Since its a Docker Image, having it on docker hub will look the best for the public and will seem more professional.

**Comment by mjadach-iv** [comment]
PR from @sitilge: Push images to docker hub #238

**Comment by nionis** [comment]
The purpose of this is to be a cosmetic change that requires doubling our docker build and push time.
I suggest we hold back from pushing this at the moment and instead focus on a better strategy.
In my opinion, the following setup is more ideal:

- build and push to GCP
- push from GCP to dockerhub (only images which are release images)

**Comment by nionis** [comment]
@sitilge we can update this issue with the new plan, feel free to close your existing PR though
