### ISSUE TITLE
Remove `hoprd_api_token` field in the output of DP

### ISSUE THREAD

**Issue by sitilge** [Rpc-h/RPCh#296]
## Expected Behavior

I don't get `hoprd_api_token` field in the output of https://staging.discovery.rpch.tech/api/v1/node .

## Current Behavior

I can still see this sensitive field.

## Steps to Reproduce

Go to https://staging.discovery.rpch.tech/api/v1/node.

Were you able to reproduce the bug using the above steps consistently each time?_ **YES**

**Comment by diegoalzate** [comment]
solved in #295
