### ISSUE TITLE
implement benchmarks part 2/2

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#307]
### Description

Implement an automated setup where we can derive benchmarks of a given release and compare them with a previous release.

- special release for benchmarks: `v1.5-benchmark` which runs on its own cluster
- produce a delta of benchmarks compared to the previous release

### Relevant issues

- [ ] create specific releases for benchmarking, and run an environment for them in our `staging` cluster
- [ ] run benchmarks once label "run:benchmark" is added and paste it in GH automatically

### Definition of DONE

Once anyone can run benchmarks for a given PR and we have benchmark specific releases.

**Comment by esterlus** [comment]
superceded by #508
