### ISSUE TITLE
RPCh Docker - deciphering message 

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#322]
## Expected Behavior

-

(Write your answer here.)

## Current Behavior

Gets req from MM, sends our req through HOPRd, is not sable to decipher what it got back.

(Write your answer here.)

## (Optional) Possible Solution

(Write your answer here.)

## Steps to Reproduce

The docker runs on Winows 11. 
It also worked fine around ETH Denver.

_Were you able to reproduce the bug using the above steps consistently each time?_ **YES**/**NO**

## Context (Environment)

(Write your answer here.)

## Detailed Description

(Write your answer here.)

## Logs

[docker-logs.txt](https://github.com/Rpc-h/RPCh/files/11171417/docker-logs.txt)

## (Optional) Possible Implementation

(Write your answer here.)

**Comment by nionis** [comment]
@mjadach-iv do you mind if we close this and re-open it if it occurs in the production version? lots of changes since then

**Comment by mjadach-iv** [comment]
Sure
