### ISSUE TITLE
Universal down time for RPCh latency monitors

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#387]
Around 13:30 UTC 02-05-2023, all requests failed on separate rpc servers.

### Client 1
![image](https://user-images.githubusercontent.com/22416585/235702010-7079fdb0-6c53-4dbf-8a43-7d7e223400d9.png)

### Client 2
![image](https://user-images.githubusercontent.com/22416585/235702166-4d2ae07d-8bc0-4134-889e-28412f6c50d7.png)

Both clients are running separate rpc servers so they _should_ be getting different entry and exit nodes.
## Expected Behavior
Each client **can** have down time but the fact that they are down at the same time with so much randomness seems wrong. 

Each client should not have down time at all and less at the same time, this is not a centralized system.

## Current Behavior
Observed 2 clients have the same downtime

**Comment by nionis** [comment]
Fixed in the new patch
