### ISSUE TITLE
Too many requests per second from clients to Discovery Platform

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#388]
From metrics we can see that more requests than normal are coming from a particular client
## Expected Behavior
A client should send only about 3 requests per minute

## Current Behavior
We see up to 108 requests per minute.

<img width="1097" alt="CleanShot 2023-05-02 at 16 56 28@2x" src="https://user-images.githubusercontent.com/22416585/235714659-a1e4a3aa-12a7-4111-b32a-866a015a4a88.png">

**Comment by diegoalzate** [comment]
I don't know if it is a wallet or rpc server user, but for sure the client is using sdk

**Comment by nionis** [comment]
Turns out the bug is a visual one in our grafana dashboard, fixed.
