### ISSUE TITLE
Detailed statistics on RPCh

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#424]
### Describe the feature you'd like

More statistics shown on the **https://grafana.rpch.tech/d/etzo-_aVz** (if possible?) such as:
- number of secrets that we generated
- number of DP calls (per client/wallet?)
- ideally also total number of packets generated
- other statistics that we can generate

### Additional context

Data will be very helpful to see the usage of RPCh, and will drive futher analitics calculations

**Comment by nionis** [comment]
Can this data be added into https://docs.google.com/spreadsheets/d/1DrP--MZ1AWJ6JYBVCtGAnGUxMvP_x0kLsEniCYWMoUg/edit#gid=1160825490 also?
