### ISSUE TITLE
Rewrite the Rust cryto into TypeScript crypto

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#425]
# Replace WASM crypto with typescript crypto

The goal here is to get the SDK to be easily integratable into other JS/TS projects.
Rewrite current crypto completely in typescript so we can remove the cumbersome crypto imports.

The API should either enforce timestamps as counters or incrementing numbers as counters, not both.

The API should prefer return codes instead of exception throwing (optional and if possible), e.g.:

```
type Result = {
    success: true,
    ...<whatever success values returned>
} | { success: false, error: string }
```

The API should provide one function call for each of the 4 steps, with the needed data as parameters. (box_request, unbox_request, box_response, unbox_response)

## Expected API (if possible) vs current API

1. boxing request

Current (timestamp counter):

```
  // Envelop only needs the target node id - see usages
  const envelope = new crypto.Envelope(data, exitId, exitId);
  const session = crypto.box_request(envelope, exitNodeReadIdentity);
```

Desired:

```
    const res = crypto.box_request(<everything needed>)
    if (Result.isError(res)) {
        // handle errors
    } else {
        // do stuff
    }
```

2. unboxing request

Current (bigint counter):

```
// Envelop only needs the target node id - see usages
const envelope = new crypto.Envelope(body, exitId, exitId);

let session;
try {
    session = crypto.unbox_request(envelope, exitNodeWriteIdentity, counter);
} catch (err) {
    return { success: false, error: `unboxing request failed: ${err}` };
}

const data = session.get_request_data();
const newCount = session.updated_counter();
```

Desired:

```
    const res = crypto.unbox_request(<everything needed>);
    ...
```

3. boxing response

Current (timestamp counter):

```
  // Envelop only needs the target node id - see usages
  const envelope = new crypto.Envelope(data, entryId, entryId);
  try {
    crypto.box_response(unboxSession, envelope);
  } catch (err) {
    return { success: false, error: `boxing response failed: ${err}` };
  }

  const hexData = utils.hexlify(unboxSession.get_response_data());
  const newCount = unboxSession.updated_counter();
```

Desired:

```
    const res = crypto.box_response(<everything needed>);
    ...
```

4. unboxing response

```
  try {
    crypto.unbox_response(
      request.session,
      new crypto.Envelope(respData, request.entryId, request.exitId),
      counter
    );
  } catch (err) {
    return { success: false, error: `unboxing response failed: ${err}` };
  }
  const data = request.session.get_response_data();
  const newCount = request.session.updated_counter();
```

Desired:

```
    const res = crypto.unbox_response(<everything needed>)
    ...
```

## Summary

- must have: implement in typescript
- nice to have: either enforce timestamps or integers as counters
- nice to have: return structs for error reporting instead of exceptions
- nice to have: concise function calls

**Comment by esterlus** [comment]
@nionis will take over

**Comment by nionis** [comment]
After discussing with the team, the library will be moved to be part of our monorepo as it going to be written in typescript

**Comment by nionis** [comment]
After syncing with @esterlus, somebody else will take over this task

**Comment by esterlus** [comment]
unfortunately not, we will have to to it ourselves somehow.. ;)
