### ISSUE TITLE
1 HOP support for availability monitor

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#427]
### Description

In preparation for 1-hop support, we would like to expand the availability monitor to further improve the selection of entry and exit nodes.

Most importantly, as we control the selection of both entry and exit nodes, we want to ensure that the given entry nodes have a high probability of their messages reaching the exit nodes.

Assumptions:

- hops = 1 (will not work with 2+ hops)
- we control all entry / exit nodes
- ~anyone can become an entry / exit node~ not in initial stable release

### Relevant issues

- new check: entry node must have X amount of outgoing open channels
- new check: exit node must have X amount of incoming open channels
- new check: given an entry now and a list of exit nodes, what are the message delivery probabilities of the entry node, must be higher than X % 
  - match the incoming and outgoing channels to find a common node
  - test connectivity between the nodes
- update get-exit-nodes DP API to allow optional insertion of an entry node, then, DP can better select exit nodes optimised for the chosen entry node

### Definition of DONE

1-HOP support is part of production environment and all necessary patches have been published

**Comment by tolbrino** [comment]
Generally a good approach. I would change the following:

- AM checks outgoing channels from entry nodes
- AM checks whether exit nodes can ping the destinations of those channels
- The intersection of nodes which are channel destinations and can be pinged from exit nodes present are used to calculate the odds to use 1-hop paths. If all work, its 100%. Any failure will lower that chance.

**Comment by nionis** [comment]
Not completed yet, until we update the DP side of things.

**Comment by nionis** [comment]
Fixed via #448 and #454
