### ISSUE TITLE
Change default port 8080 to 8547 

### ISSUE THREAD

**Issue by Jaguaras** [Rpc-h/RPCh#435]
### Is your feature related to a problem?

Port 8080 is commonly used by other services, which may require users to change ports.

### Describe the feature you'd like

We suggest changing to port 8547, which is more unique. Additionally, since port 8546 is used for WS, it would make sense to use the next number (8547) for RPCh.

**Comment by esterlus** [comment]
RPCh now comes with 45750 as its default port
