### ISSUE TITLE
Rpch servers are unstable which leads to unstable connections

### ISSUE THREAD

**Issue by trincema** [Rpc-h/RPCh#443]
It happens very often that the Rpch connection cannot be establish. The cause seem to be RpcUsually they have to be manually restarted. Sometimes, however, I've even seen some errors in the terminal running Rpch docker command. See attached screenshots.

## Expected Behavior
Stable Rpch connections.

## Current Behavior
Unstable Rpch connections.

## (Optional) Possible Solution
Have to investigate these unstabilities and fix the issues causing them, but that is probably not that easy to reproduce.

## Steps to Reproduce
1. Start Rpch docker container
2. Go to MM and try to establish a connection

_Were you able to reproduce the bug using the above steps consistently each time?_ YES

## Context (Environment)
Really hard to test and detect why some issues happened, could be confusing if the connection is unstable.
Hard to setup connection in MM because of this.

## Detailed Description
- Device: Asus, Thinkpad, iMac
- OS: Ubuntu 20/22, MacOSX
- Browser: chrome
- Version: 114

## Logs
![8f750219-9caa-49d9-89e9-697562e968b5](https://github.com/Rpc-h/RPCh/assets/7762113/d1f9dce6-1f10-4a47-bbb1-8b6668b15360)
![image](https://github.com/Rpc-h/RPCh/assets/7762113/51689ee8-e6f4-4432-9021-8c7cf6e80b6e)

**Comment by SCBuergel** [comment]
Here logs of my MM connection failure.
Protocol:
1. Add RPCh server to MM as custom network and activate that network, I am using `http://10.137.0.51:8080/?exit-provider=https://rpc.ankr.com/eth`
2. Close browser in which MM is running
3. Start latest version of RPCh server from website. That is currently

```
docker run -e DEBUG="rpch*,-*metrics" -e RESPONSE_TIMEOUT=5000 -e DISCOVERY_PLATFORM_API_ENDPOINT=https://staging.discovery.rpch.tech -e PORT=8080 -e DATA_DIR=app -e CLIENT=handsome-rest-combine-kept-variety  --name rpc-server -p 8080:8080 --rm  europe-west6-docker.pkg.dev/rpch-375921/rpch/rpc-server:6b9862f
```

4. wait 1 minute
5. start browser and unlock MM. It should now attempt to connect to RPCh server.
The last step consistently fails for me with `We can't connect to RPCh mainnet`. Debug output below:
[rpch_debug_output_seb.txt](https://github.com/Rpc-h/RPCh/files/11919388/rpch_debug_output_seb.txt)

Just to be on the safe side that this works in general I tested via `curl` and indeed all is well:
```
$ curl 10.137.0.51:8080/?exit-provider=https://rpc.ankr.com/eth -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}'
{"id":1,"result":"0x1","jsonrpc":"2.0"}
```
