### ISSUE TITLE
MM Firefox Rpch connection not working

### ISSUE THREAD

**Issue by trincema** [Rpc-h/RPCh#444]
I was trying at least a dozen times to connect to Rpch from Firefox and it just doesn't work. Connecting to Ethereum works, so MM is working fine in FF, but Rpch connection doesn't. See attached video of the issue.

## Expected Behavior
MM FF Rpch connection should be possible.

## Current Behavior
MM FF Rpch connection doesn't work.

## Steps to Reproduce
1. Start Rpch docker container locally
2. Setup MM in FF and setup Rpch network
3. Try to connect to Rpch network

_Were you able to reproduce the bug using the above steps consistently each time?_ YES

## Detailed Description
- Device: Lenovo Thinkpad
- OS: Ubuntu Lts20
- Browser: Firefox
- Version: 114.0.2

## Logs
https://github.com/Rpc-h/RPCh/assets/7762113/23859468-e6bd-49ac-9ae1-6325db1cb117

**Comment by esterlus** [comment]
We know about MM duplicate chainID problems and have implemented better instructions on our website when they happen
