### ISSUE TITLE
Battle testing

### ISSUE THREAD

**Issue by esterlus** [Rpc-h/RPCh#508]
# Battle Testing

Develop a better way of testing real world traffic to gather reliable usage scenario numbers and determine network capabilities.

## Current testing strategies

Inside `devkit/loadtesting-k6/` we have some loadbalancing capabilities.

Run them via `yarn start:<testname>` where testname currently allows:

- `spike-small` - run 100 concurrent users with minimal message
- `spike-large` - run 100 concurrent users with maximal real message
- `stress-small` - run 50 concurrent users with minimal message
- `stress-large` - run 50 concurrent users with maximal real message
- `soak-small` - run 20 concurrent users with minimal message
- `soak-large` - run 20 concurrent users with minimal message
- `soak-large` - run 20 concurrent users with minimal message
- `realtraffic-small` - run 50 concurrent users over 30m with minimal message and 1 sek pause between messages

NOTE: realtraffic is the worst name here because it is as far away from what it does as one can imagine.

All tests are usually executed against a local running rpc server from a local machine.

## Target setup

- [x] #509
- [x] #510

spike test - huge number of users short time
stress test - system limit longer time
soak test - long running low system resources

* Determine the number of max concurrent users while the network keeps working reliably

**Comment by mjadach-iv** [comment]
Done
