### ISSUE TITLE
Making RPCh Docker server work on https 

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#511]
### Is your feature related to a problem?

There are issues adding a http://localhost:45750/?provider=https://<URL> RPC endpoint to the settings within [app.safe.global](http://app.safe.global/) (and we can assume the same goes for other web apps that allow me to customize an RPC endpoint). Most likely the issue is that you cannot mix HTTP & HTTPS content. 

### Describe the feature you'd like

Automatically generated SSL cert, so RPCh cloud also work on https://localhost:45751

### Alternative solution

We could have some kind of extra container command that will start a reverse proxy as an additional container that generates an ssl cert and forwards requests to rpc-server container.
Could be part of some kind of `extra` section on the webpage.

**Comment by SCBuergel** [comment]
Trying to set the environment variable of my Safe web UI to my local RPCh instance gives me the following error:
```
Mixed Content: The page at 'https://app.safe.global/settings/environment-variables?safe=eth:0x752af2Bf9DbBC1105a83D2CA1eE8F1046D85B702' was loaded over HTTPS, but requested an insecure resource 'http://10.137.0.33:45750/?provider=https://ethereum-provider.rpch.tech'. This request has been blocked; the content must be served over HTTPS.
```

(ignore the weird looking IP, this is a localhost qubes VM which is accessible to that VM as evidenced e.g. by Frame using it)

![rpch](https://github.com/Rpc-h/RPCh/assets/11379673/2f0223c9-12f5-4cdd-8773-94032ae0eac0)

**Comment by SCBuergel** [comment]
Another point in case: Zeal.app (browser extension wallet) only works with HTTPS endpoints for RPC providers.
![Zeal](https://github.com/Rpc-h/RPCh/assets/11379673/a64afcc4-3ece-44cd-88ed-46c904cea4b0)
