### ISSUE TITLE
implement testing environment part 2

### ISSUE THREAD

**Issue by nionis** [Rpc-h/RPCh#73]
### Description

Expand the testing environment with the support of the Discovery Platform and Funding Service.
Continuation of #69, blocked by #38 and #42 

### Relevant issues

- [x]  include Discovery Platform

- [x] include Funding Service
- [x] update E2E tests

### Definition of DONE

Once we have a single script where we can locally run an RPCh ecosystem.

**Comment by SCBuergel** [comment]
@diegoalzate what's the state on this one?
